name = "https-itsu-dev2-workers"
main = "src/index.ts"
compatibility_date = "2024-12-06"

[[d1_databases]]
binding = "DB"
database_name = "https-itsu-dev2"
database_id = "15a35e49-7ee8-4f53-80e1-37a2f0c7c2cf"